export default [
  /* {
    text: "新生",
    url: "/sub-freshman/pages/welcome/welcome",
    iconPath: "../../assets/icons/index/freshman.png",
    needVerify: false
  },*/ {
    text: "电费",
    url: "/sub-electricity/show/show",
    iconPath: "../../assets/icons/index/electricity.png",
    needVerify: false
  }, {
    text: "空教室",
    url: "/sub-classroom/classroom",
    iconPath: "../../assets/icons/index/availroom.png",
    needVerify: false
  }, {
    text: "课表",
    url: "/sub-timetable/pages/index/index",
    iconPath: "../../assets/icons/index/timetable.png",
    needVerify: true
  }, {
    text: "常用电话",
    url: "/sub-phonebook/phonebook",
    iconPath: "../../assets/icons/index/telephone.png",
    needVerify: false
  }, /* {
    text: "成绩",
    url: "/sub-score/pages/index/index",
    iconPath: "../../assets/icons/index/score.png",
    needVerify: true
  }, {
    text: "活动",
    url: "/sub-activity/pages/index/index",
    iconPath: "../../assets/icons/index/activity.png",
    needVerify: true
  }, {
    text: "商城",
    url: "/sub-shop/pages/index/index",
    iconPath: "../../assets/icons/index/shop.png",
    needVerify: true
  } */
];
